version: '3.9'
services:
  flask:
    container_name: flask
    build: .
    ports:
      - "4711:5000"
    volumes:
      - /volume1/docker/maschinenplan:/app
    restart: unless-stopped

